### ISSUE TITLE
Unsafe in get_pair_mut

### ISSUE THREAD

**Issue by ramn** [saschagrunert/indextree#1]
I noticed there is a usage of unsafe in get_pair_mut. Do you think this could be avoided by using &[].split_at_mut()? Something along the lines of

```rust
let (xs, ys) = self.split_at_mut(max(a, b));
(&mut xs[min(a, b)], &mut ys.first)
```

**Comment by saschagrunert** [comment]
Thank you very much for your feedback, actually this does not work because we also have to swap the return order of `xs` and `ys`. Something like this could work:

```rust
let (xs, ys) = self.split_at_mut(std::cmp::max(a, b));
if a < b {
    (&mut xs[a], &mut ys[0])
} else {
    (&mut ys[0], &mut xs[b])
}
```

**Comment by ramn** [comment]
https://github.com/saschagrunert/indextree/pull/2
