### ISSUE TITLE
[Feature Request] Implement `DoubleEndedIterator` for plain iterators

### ISSUE THREAD

**Issue by alexmozaidze** [saschagrunert/indextree#106]
It would be beneficial to implement [`DoubleEndedIterator`] for iterators that do not traverse depth-wise, like [`Children`], [`FollowingSiblings`] and [`PrecedingSiblings`].

[`DoubleEndedIterator`]: https://doc.rust-lang.org/std/iter/trait.DoubleEndedIterator.html
[`Children`]: https://docs.rs/indextree/latest/indextree/struct.Children.html
[`FollowingSiblings`]: https://docs.rs/indextree/latest/indextree/struct.FollowingSiblings.html
[`PrecedingSiblings`]: https://docs.rs/indextree/latest/indextree/struct.PrecedingSiblings.html

**Comment by saschagrunert** [comment]
Hey @alexmozaidze, I agree. Do you plan to contribute that feature?

**Comment by alexmozaidze** [comment]
I never implemented this trait, but considering that `Node` already has methods to go forwards and backwards between siblings, it shouldn't be hard. I might take a whack at it in my spare time.

**Comment by alexmozaidze** [comment]
Resolved as of merging of #107
