### ISSUE TITLE
Parallel tree traversal

### ISSUE THREAD

**Issue by tilacog** [saschagrunert/indextree#11]
Hi there!

The README mentions _parallel tree traversals_ over an `Arena` but I couldn't find any related method on the docs.

How could one do so?

Also, are there any plans to support [rayon](https://github.com/rayon-rs/rayon)'s parallel iterators ?

Great lib, btw :+1:

**Comment by saschagrunert** [comment]
Hey, currently there is no real parallel iteration support yet for this library. I added this in 021f3382a67a0bf8fa73c55e77c72b2e253ce8c0 and v2.0.0.
