### ISSUE TITLE
Bad NodeId.index?

### ISSUE THREAD

**Issue by ArnaudValensi** [saschagrunert/indextree#14]
You are using ˋself.nodes.len()` to get the next index, but if you add 2 nodes, then remove the first one, then add a node, both nodes will have the same index right ?

**Comment by saschagrunert** [comment]
How would you remove a node? :)

**Comment by ArnaudValensi** [comment]
Ok, if my understanding is correct, this data structure is not meant to move or remove nodes. It does not fit my usecase, but your code is inspiring for my needs. Thanks.

**Comment by saschagrunert** [comment]
Yes, it would be possible to add this feature but implies a bit more garbage collection. Maybe in the future. :) thank you for the feedback.
