### ISSUE TITLE
Panic on semantic error, rather than returning error?

### ISSUE THREAD

**Issue by lo48576** [saschagrunert/indextree#29]
It seems `indextree` avoids panicking, even if there are semantic error (caused by broken inconsistent data).

For example:
https://github.com/saschagrunert/indextree/blob/0e512954beba93e1fcfcf004cc69b1419298b89c/src/lib.rs#L460-L471
In this code, if `self_borrow.last_child` was `None`, `self_borrow.first_child` should be also `None`, if `indextree` is working correctly.
If it is not, then the data can (and may) have been broken in unexpected way, and it seems meaningless to do more operation on that broken data.
Additionally, results are returned as `Fallible<_>` and it does type erasure, so users might easily miss such semantic bug.

I think semantic errors should be caught by panicking (typically `.expect()` on `Result` and `Option`) and assert macros.

**Comment by saschagrunert** [comment]
Hey @lo48576 :wave: thanks for the issue report. Do you mind proposing a change as PR? :)

**Comment by lo48576** [comment]
I'll try to write a PR.
