### ISSUE TITLE
Accessing nodes on a given Arena

### ISSUE THREAD

**Issue by bright-star** [saschagrunert/indextree#3]
How do you get access to an iterator on an Arena? For example, if a function returns a created Arena with appended Nodes, how do I start traversing or indexing? According to the docs, Arena itself doesn't seem to have any methods that let you do this without an appended NodeId included separately.

**Comment by TheDan64** [comment]
I agree, I ran into this issue recently. I wanted to count the number of nodes in the arena and there doesn't seem to be a node-agnostic way of doing do. I expected to be able to do `arena.iter().count()`. Maybe iterating over the tree in some unspecified internal order isn't commonly useful, so having a len method on arena would at the very least be useful to my particular scenario.

**Comment by saschagrunert** [comment]
Alrighty, does #4 solve the problem for the certain use case?

**Comment by TheDan64** [comment]
For me, totally! Thanks!
