### ISSUE TITLE
Should insertions return `Result` type?

### ISSUE THREAD

**Issue by lo48576** [saschagrunert/indextree#42]
Insertions can fail if the preconditions are not met, but they are very very simple.
Preconditions:

* `NodeId::append()`,  `NodeId::prepend()`:
    + `self != new_child`.
* `NodeId::insert_before()`, `NodeId::insert_after()`:
    + `self != new_sibling`.

They are sometimes ensured by the context, and then users are sure insertions do not fail.
In such situation, it seems redundant to unwrap many results.
(See <https://github.com/saschagrunert/indextree/pull/39/files#diff-e7bc1f36b79d2e2d0030318c5fe20910> for example.)

I'm not sure which is better...
Both interface (panicking or not panicking when preconditions are not met) seems reasonable.

**Comment by lo48576** [comment]
If both interfaces are provided, it may be useful (e.g. we can choose `arr[i]: &T` or `arr.get(i): Option<&T>`).

**Comment by lo48576** [comment]
[`isize::abs()`](https://doc.rust-lang.org/stable/std/primitive.isize.html#method.abs) may panic for certain input, and [`isize::checked_abs()`](https://doc.rust-lang.org/stable/std/primitive.isize.html#method.checked_abs) is safer version returning `None` instead of panicking for invalid input.

It seems good idea to having both `checked_append() -> Result<(), NodeError>` and `append() -> ()`.

**Comment by saschagrunert** [comment]
> It seems good idea to having both `checked_append() -> Result<(), NodeError>` and `append() -> ()`.

Yes I like the idea having both, too. 👍
