### ISSUE TITLE
Problems around CI stuff

### ISSUE THREAD

**Issue by lo48576** [saschagrunert/indextree#47]
Files introduced by #45.

## About `.gitignore`:
> If you’re building a non-end product, such as a rust library that other rust packages will depend on, put `Cargo.lock` in your `.gitignore`.
>
> --- [Cargo.toml vs Cargo.lock - The Cargo Book](https://doc.rust-lang.org/cargo/guide/cargo-toml-vs-cargo-lock.html)

If CI really needs the lockfile, it should be prepared by the CI script, instead of including `Cargo.lock` to the project.
(For example, include `Cargo.lock.ci` to the project and rename it to `Cargo.toml` before the build phase runs.)

## About `.rustfmt.toml`:

`.rustfmt.toml` should have only non-default entries, or empty.
If it has unstable entries (such as `indent_style`), they prevents stable `rustfmt` from using the config, and `required_verison = "1.0.3"` prevents other nightly rustfmt from formatting the code.

I think using default config is the best, and then `.rustfmt` can be removed.

**Comment by saschagrunert** [comment]
I agree and will spin up a PR fixing this.
