### ISSUE TITLE
Clarify order of Descendants, Traverse, and ReverseTraverse

### ISSUE THREAD

**Issue by clbarnes** [saschagrunert/indextree#55]
I've had a look around and it doesn't seem like "tree order" has any meaning when it comes to graph traversal - rather, it relates to the number of children each node can have. The language in common use for tree traversal seems to be "depth first" and "breadth first", in "pre order", "post order", or "level order".

**Comment by saschagrunert** [comment]
Hey, this sounds like a good documentation enhancement to me. Do you mind spinning up a PR to fix it? :)

**Comment by clbarnes** [comment]
Seems like they're all a pre-order depth first search, the only distinction being that `descendants` yields `NodeId`s (not `&Node`s as the current docs imply); `traverse` yields `NodeEdge`s containing `NodeId`s (again, not `&Node`s) in depth-first order, addressing the children in insertion order; `reverse_traverse` addresses children in reverse insertion order. `traverse` and `reverse_traverse` visit each node twice (once before its children, once after).
