### ISSUE TITLE
Easier access to underlying index

### ISSUE THREAD

**Issue by wlinna** [saschagrunert/indextree#57]
I need to access the underlying index of a `NodeId`.

Background:
I'm using `indextree` to implement an octree. Each node should also know which nodes are not visible from that node. My `NodeData` looks like this:

```
pub struct NodeData {
   ... 
    pub occludees: Vec<NodeId>
}
```

Now I need to serialize my tree in JSON format, but the problem is that I cannot access `NodeId`'s underlying index. I also tried to use `Serialize` attribute (after activating `deser` feature), which gets me somewhere, but the index is serialized as following

```
{
     "index1": 51
}
```

Would it be possible to add an easy way to access the underlying index? 
Thanks!

**Comment by saschagrunert** [comment]
Hey, thank you for the request. We could make this method public to retrieve the usize:
https://github.com/saschagrunert/indextree/blob/cf9d9f277c587c7d51333fc8c71dc22a3b04310d/src/id.rs#L39

But I think it would be cleaner if we implement a [`std::convert::Into`](https://doc.rust-lang.org/std/convert/trait.Into.html) for `usize` do you mind opening a PR for that kind of feature?

**Comment by wlinna** [comment]
Thanks for your quick response!

I'm still a beginner when it comes to Rust, but this doesn't seem too difficult, so I'll open a PR when I've done it – probably tomorrow.

**Comment by saschagrunert** [comment]
Awesome, let me know if you need any support and we push it over the line together. :)

**Comment by wlinna** [comment]
I suppose this issue can be closed now

**Comment by sensiblearts** [comment]
@wlinna Hello, my name is David and I'm new to Rust and I'm hoping that you can point me in the right direction:

I'm trying to find a generic, serializable Tree structure, and it looks like `indextree` might let me create a tree of `MyNode` structs, where each MyNode has `#[derive(Serialize)]`, such that if I call a `serde` macro, `json!(tree)`, the entire tree will be serialized to json.

Questions:
1. Will I have to write my own recursive traversal code?
2. If (1), then should I fork `indextree` and try to add `to_json` functionality; or is that not advised?
3. If neither of the above, how might I get the following code working?

```rust
#[derive(Debug)]
#[derive(Serialize)]
pub struct Node {
    pub name: String,
}
// ...

    let n2 = Node{name: "Dave".to_string()};
    let n3 = Node{name: "Sarah".to_string()};

    let mut arena : Arena<&Node>  = Arena::new();

    let a = arena.new_node(&n2);
    let b = arena.new_node(&n3);

    // Append a to b
    a.append(b, &mut arena);

    assert_eq!(b.ancestors(&arena).into_iter().count(), 2);

    println!("arena {:?}", json!(arena));  // This will not compile
```
The error message for why that last line won't compile:

```
the trait bound `Arena<&Node>: Serialize` is not satisfied
for local types consider adding `#[derive(serde::Serialize)]` to your `Arena<&Node>` type
for types from other crates check whether the crate offers a `serde` feature flag
the following other types implement trait `Serialize`:
  &'a T
  &'a mut T
  ()
  (T,)
..etc..
```
and `toml`:
```
[dependencies]
indextree = "4.7.4"
nary_tree = "0.4.3"
serde = { version = "1.0.219", features = ["derive"] }
serde_json = "1.0.140"
```
Thanks for any advice.
